apiVersion: v1
kind: Secret
metadata:
    name: ircbot
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: opaque
stringData:
    SUPYBOT_OWNER_NAME: ENC[AES256_GCM,data:2MZ/cO+i,iv:v5oK71u3H6k63zhdDqpGNyIThz8Lqcx4iJlvreJqa+U=,tag:UShJsnWS8wsUljEaSGZdQA==,type:str]
    SUPYBOT_OWNER_PASSWORD: ENC[AES256_GCM,data:OIiUg5/KTMFgzzyhiDaOT5U4d2seLUw+Zg==,iv:qmcYvMr9L/ShVfPgwYeb/V7mfLOH43UfI0Z2p/odUzs=,tag:jvIMgvt4tfWVUPVlnvLkpA==,type:str]
    SUPYBOT_SASL_PASSWORD: ENC[AES256_GCM,data:VgMSRPRf9Rmzwjy49YsT8BxhLgvDVL0MZg==,iv:Cml7pDJBJU3IYeDXCZI0t7e9+hLCE7j7JEA7/VZyZ8Q=,tag:Uc20luhXNOkOTu2OnevRcQ==,type:str]
    GH_SECRET_TOKEN: ENC[AES256_GCM,data:q6oy0Wux8UwyxcKQKBJNlkArHJ7VrIbSCw==,iv:tfqwPKJwSlGHl+Dj4tlB5YNhmFvaGONcGfVO83w07g8=,tag:C5tYPHHwytlOImpvAyPvqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-30T01:04:52Z'
    mac: ENC[AES256_GCM,data:DAod8mZdSeIlRqTb2RD2BvrU9D1gVmjScC1UsdnIvaPSJLlGkCktHl88bvMKyL2CgMuiHuSSBn1Uf3sv9OSvH/4lz0MwSMePAWNCsQeSxAubRrHcPMBs4U/IjCXZjMz/M23UfPQZX6JLL4OfzfnokjZd6Wf9GFzEiSUZMqhuBgM=,iv:hmad1gyKNwzE2oe2/pXpjn6MIIgLShMDpFnWek89knQ=,tag:TnDPG5dcbSYAwJSz/QwskA==,type:str]
    pgp:
    -   created_at: '2020-10-29T21:24:02Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA0Jtk4Lf1qepAQgAkveJKM7rKS98bX8I27QHQtMt72Emf5nf6H3B3ziuv5+z
            sz9dNVDgw6PDC+IMLli0+k2oLC59ELRT0MjLSQ/rkTbFcSQ4cJbqHJanFvj0KGBQ
            27M9vEVPoQ7f8G7skNhyhhPmlHmjp0Yoi8IXSM3kU42EBPWGjEdX4x7BWPLWU5MF
            i8XFv2eNVd/ca4iR7VxZs8tRiqRXB/Lo7D0IJ+fIXPU9BugE5pZP84cwSAamyAfO
            HOEgDNRgcIVLqhzH4AlD0A+MFFAYfHTZ/CFCdcBlt6XokBI0C0pBLtwDaqRNdsIo
            34AZQmxkJBVi+PzdwUcSQtFdonU37zs4y+pf7zAv+NLgAeSzF8Y1cFMm6nzEmBnY
            8+Nn4bn04Njgt+F36OAg4t7I1XPglOV5/wcQpcWFkejvarRo3HLiRjr3YShwC4+A
            wWciyffgNOC35FsVuz7rIWmRSuqKnjf1+Irizb8aROEDVQA=
            =tQE/
            -----END PGP MESSAGE-----
        fp: 3E70A502BB5255B6BB8E86BE362D63A80853D4CF
    encrypted_regex: ^(data|stringData)$
    version: 3.6.0
