apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gh-hook-receiver
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: gh-hook-receiver
    weight: 100
  wildcardPolicy: None
