apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supybot-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 5Gi
